### ISSUE TITLE
Postcss-modules-* dependencies

### ISSUE THREAD

**Issue by btzr-io** [buttercomponents/butter-component-builder#11]
I'm not sure where or why we use this?

- `"postcss-modules-extract-imports": "^1.0.0"`,
- `"postcss-modules-local-by-default": "^1.0.1",`
- `"postcss-modules-scope": "^1.0.0",`
- `"postcss-modules-values": "^1.1.1",`
 
> update: They are related with postcss ( plugins ) ,
Since we don't use it anymore we should remove them.

**Comment by xaiki** [comment]
you're the CSS master on this branch.

**Comment by btzr-io** [comment]
https://github.com/buttercomponents/butter-component-builder/pull/12
