### ISSUE TITLE
npm install ( bug )

### ISSUE THREAD

**Issue by btzr-io** [buttercomponents/butter-component-builder#13]
I though it was stuck but I debugged it with `procmon` and it says it's staging `material-design-icons`
```
npm install
extract:rxjs: verb gentlyRm don't care about contents;
```
> After 20 minutes of installation, it shows several errors and ultimately does not get installed.

- issue: https://github.com/google/material-design-icons/issues/518

#
npm: 4.5.0
node: v6.10.3
OS: Microsoft Windows [Version 10.0.14393]

**Comment by btzr-io** [comment]
it's been 30 minutes since get stuck and still staging material-icons...

**Comment by btzr-io** [comment]
it's done after 35 minutes, we only need the fonts not svg / png / android / ios.

**Comment by btzr-io** [comment]
@xaiki we should use this [material-iconfont](https://github.com/luhuiguo/material-iconfont)

**Comment by xaiki** [comment]
@btzr-io patches welcome

**Comment by btzr-io** [comment]
@xaiki this should reduce installation time / size : https://github.com/buttercomponents/butter-component-builder/pull/14

**Comment by xaiki** [comment]
fixed
