### ISSUE TITLE
Load themes from butter-desktop

### ISSUE THREAD

**Issue by btzr-io** [buttercomponents/butter-component-builder#16]
We should load themes  from `butter-desktop` instead of `component-builder`,
so you don't have to rebuild the component each time you update `themes` / `base-theme`:
```HTML
<link rel="stylesheet" id="theme" href="../../node_modules/butter-theme-dark/index.css">
```

**Comment by xaiki** [comment]
should we ? don't we want self-contained themes ? isn't base theme to 'just make it look right' ?
